spring:

  jpa:
    show-sql: true    # sql 쿼리 출력
    properties:
      hibernate:
        format_sql: true    # sql 예쁘게 출력하기
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect

  datasource:
    url: jdbc:h2:mem:testdb

    hikari:
      jdbc-url: jdbc:h2:mem:testdb;MODE=MYSQL

  h2:
    console:
      enabled: true

#대충 이그노어 테스트