name: CI  # 워크플로의 이름

# 워크플로 시작 조건
on:
  pull_request:
    branches: [ main ]

env:
  S3_BUCKET_NAME: profileem-backend


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # submodule에 있는 파일 최신으로 업데이트
      - name: Update Submodule
        run: git submodule update --init --recursive

      - name: Build with Gradle
        run: ./gradlew clean build
